/** **************************** Export Update Users Types ****************************** */
export const UPDATE_ORGANIZATION_USERS_SUCCESS = "UPDATE_ORGANIZATION_USERS_SUCCESS";
export const UPDATE_ORGANIZATION_USERS_FAILURE = "UPDATE_ORGANIZATION_USERS_FAILURE";
export const UPDATE_ORGANIZATION_USERS_REQUEST = "UPDATE_ORGANIZATION_USERS_REQUEST";
export const CLEAR_UPDATE_ORGANIZATION_USERS_STATE = "CLEAR_UPDATE_ORGANIZATION_USERS_STATE";
