/** **************************** Export Update Users Types ****************************** */
export const UPDATE_SYSTEM_USERS_SUCCESS = "UPDATE_SYSTEM_USERS_SUCCESS";
export const UPDATE_SYSTEM_USERS_FAILURE = "UPDATE_SYSTEM_USERS_FAILURE";
export const UPDATE_SYSTEM_USERS_REQUEST = "UPDATE_SYSTEM_USERS_REQUEST";
export const CLEAR_UPDATE_SYSTEM_USERS_STATE = "CLEAR_UPDATE_SYSTEM_USERS_STATE";
