/** **************************** Export Update Users Types ****************************** */
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILURE = "UPDATE_ORGANIZATION_FAILURE";
export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const CLEAR_UPDATE_ORGANIZATION_STATE = "CLEAR_UPDATE_ORGANIZATION_STATE";
