/** **************************** Export Create User Types ****************************** */
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILURE = "CREATE_ORGANIZATION_FAILURE";
export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CLEAR_CREATE_ORGANIZATION_STATE = "CLEAR_CREATE_ORGANIZATION_STATE";
